name: Collect Commit Stats

on:
  schedule:
    - cron: "0 */6 * * *" # Alle 6 Stunden
  workflow_dispatch: # Manuelles Auslösen

jobs:
  collect-commit-stats:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install requests

    - name: Run Commit Script
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        python3 scripts/commitCollectionScript.py

    - name: Save Stats as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: commit-stats
        path: stats.json
