name: Collect Stats

on:
  schedule:
    - cron: "0 */6 * * *" # Alle 6 Stunden
  workflow_dispatch: # Manuelles Auslösen

jobs:
  collect-commit-stats:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt

    - name: Run Commit Collection Script
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        python3 scripts/statsCollectionScript.py

    - name: Check for Changes
      id: check_changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "CHANGES=true" >> $GITHUB_ENV
        else
          echo "CHANGES=false" >> $GITHUB_ENV
        fi

    - name: No changes found
      if: env.CHANGES == 'false'
      run: |
        echo "No changes found!"

    - name: Push Results to Repository on chnages
      if: env.CHANGES == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add stats.json
        git commit -m "Update total commits in stats.json"
        git push
      
