metrics:
  permissions:
    contents: write
  steps:
    - uses: lowlighter/metrics@latest
      with:
        output_action: commit
        committer_branch: metrics-renders
        committer_message: "chore: update metrics"
