metrics:
  permissions:
    contents: write
  steps:
    - uses: lowlighter/metrics@latest
      with:
        output_action: commit
        committer_branch: metrics-renders
        committer_message: "chore: update metrics"
        plugin_languages: yes
        plugin_languages_sections: recently-used
        plugin_languages_recent_load: 400
        plugin_languages_recent_days: 14
